version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: dulapahv-portfolio:latest
    container_name: dulapahv-portfolio
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # For hot reload in development
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - portfolio-network

  # Development version with hot reload
  dev:
    image: node:20-alpine
    container_name: dulapahv-portfolio-dev
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge