name = "dulapahv-portfolio"
pages_build_output_dir = ".open-next"
main = ".open-next/worker.js"
compatibility_date = "2025-10-05"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "dulapahv-portfolio"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "dulapahv-portfolio-cache"
