import type { Metadata } from "next";
import { ReactNode } from "react";
import dynamic from "next/dynamic";
import { Poppins, Raleway } from "next/font/google";
import Head from "next/head";
import { ThemeProvider } from "next-themes";

import { Navbar } from "@/components";

import "./globals.css";

import { Providers } from "./providers";

const noDarkReader = dynamic(() => import("no-darkreader"), { ssr: false });

// const poppins = Poppins({ weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ["latin"] });
const raleway = Raleway({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DulapahV's Portfolio",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className="min-h-screen bg-default-50 text-default-800"
    >
      <Head>
        {/* Disable Dark Reader Plugin */}
        <meta name="darkreader" content="NO-DARKREADER-PLUGIN" />
      </Head>
      <body className={`my-4 max-w-7xl px-16 mx-auto ${raleway.className}`}>
        <ThemeProvider>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
