import type { Metadata } from "next";
import { ReactNode } from "react";
import dynamic from "next/dynamic";
import { Poppins, Raleway } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import { ThemeProvider } from "next-themes";

import { Navbar } from "@/components";

import "./globals.css";

import { Providers } from "./providers";

const noDarkReader = dynamic(() => import("no-darkreader"), { ssr: false });

// const poppins = Poppins({ weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ["latin"] });
const raleway = Raleway({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DulapahV's Portfolio",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className="min-h-screen text-default-800"
    >
      <Head>
        {/* Disable Dark Reader Plugin */}
        <meta name="darkreader" content="NO-DARKREADER-PLUGIN" />
      </Head>
      <body
        className={`mx-auto my-4 max-w-7xl px-16 antialiased ${raleway.className}`}
      >
        <div className="fixed -right-[35%] -top-[25%] -z-50 size-full select-none overflow-clip opacity-50 mix-blend-darken hue-rotate-[45deg] dark:mix-blend-lighten sm:rotate-[20deg]">
          <Image src="/grad-right.png" alt="grad-left" fill />
        </div>
        <div className="fixed -bottom-[15%] -left-[25%] -z-50 size-[80%] select-none overflow-clip opacity-50 mix-blend-darken dark:mix-blend-lighten sm:rotate-[15deg]">
          <Image src="/grad-left.png" alt="grad-left" fill />
        </div>
        <ThemeProvider>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
