name: CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: |
          pwd  # Print current directory
          ls   # List contents of the current directory
      - run: |
          cd $GITHUB_WORKSPACE
          yarn install --frozen-lockfile
      - run: |
          cd $GITHUB_WORKSPACE
          yarn build
